---
title: "Dados ISS (2020-2021)"
subtitle: "Secretaria de Planejamento do Estado do Ceará - Seplag"
author: "Gerrio Barbosa"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      titleSlideClass: [top, left, inverse]
      #countdown: 60000  # coloca o tempo -- que fica vermelho quando termina
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)

style_xaringan(
  background_color = "white",
  #header_color = "#488430",
  #header_background_color = "#488430",
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "300", "300i"),
  code_font_google   = google_font("Fira Mono")
)
```

```{r}
#devtools::install_github("gadenbuie/xaringanExtra")
library(xaringanExtra)

xaringanExtra::use_logo(
  image_url = "https://raw.githubusercontent.com/rstudio/hex-stickers/master/PNG/xaringan.png",
  position = xaringanExtra::css_position(top = "1em", right = "1em")

)

```

---

# Cidade - CE


```{r include=FALSE}
library(tidyverse)
library(extrafont)

df_mun <- haven::read_dta('DadosISS_bimestral.dta') %>%
  mutate(Bimestre = case_when(
    Bimestre == 1 ~ '1˚ Bimestre',
    Bimestre == 2 ~ '2˚ Bimestre',
    Bimestre == 3 ~ '3˚ Bimestre',
    Bimestre == 4 ~ '4˚ Bimestre',
    Bimestre == 5 ~ '5˚ Bimestre',
    Bimestre == 6 ~ '6˚ Bimestre'
  ),
  iss19 = round(ISS19/pop19, 2),
  iss20 = round(ISS20/pop19, 2)) %>%
  select(Municipio, Bimestre, 'ISS por Habitante 2019' = iss19, 'ISS por Habitante 2020' = iss20) %>%
  pivot_longer(cols = !Municipio:Bimestre, names_to = 'iss', values_to = 'iss_pop') %>%
  filter(Municipio %in% c('CE-Coreaú'))

```



```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width = 7, fig.height = 5, dpi=300}
library(tidyverse)
library(extrafont)

df_mun %>%
  ggplot(aes(x = Bimestre, y = iss_pop, fill = iss)) +
  geom_bar(stat = 'identity', position = position_dodge(),
           color = 'white')+
  #ggtitle(dados$Municipio)+
  theme_minimal()+
  coord_flip()+
  scale_y_continuous(n.breaks = 10)+
  scale_fill_manual(values = c('#58D68D', '#58D68D'))+
  theme(#text = element_text(family="Times New Roman", color="black",
        #                    size=30, face="bold"), 
        legend.position = 'none', panel.grid = element_blank())+
  labs(subtitle = '',
       x = '', y = '',
       caption = 'Observatório do Federalismo Brasileiro (OFB) \n @seplagce',
       tag = '', fill = '') + facet_wrap(~iss)

```




<!-- ```{r} -->
<!-- library(tidyverse) -->
<!-- df_estado %>% ggplot(aes(ano, valor))+geom_line() -->


<!-- ``` -->



